### ISSUE TITLE
Include the mode of "Preparation" in the kitchen count

### ISSUE THREAD

**Issue by BeatriceDaudelin** [santropolroulant/sous-chef#108]
As a Roulant administrative employee I would like be able to generate the kitchen count with in it the list of clients needing a specific "Preparation" that day.

## Acceptance criteria

- Food preparation is added into the 'Clashing ingredients' table, per client.
- Food preparation is also listed in a separated table, for client not having clashing ingredients.
- The mode of "Preparation" need to follow any change made on the profil of the client in Sous Chef

**Comment by guillaumep** [comment]
Released in v1.4.1.
