### ISSUE TITLE
Windows OS unexpected behavior

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [santropolroulant/sous-chef#12]
### Expected Behaviour

When creating an order for a client that already has one, the app prompts the user to validate the overriding of the existing order before replacing it.

The UI then shows a green alert on top of the screen that reads: 1 order(s) successfully placed for Mrs. So and So.

When done with Firefox/Linux everything seems stable. The app seems to perform as needed

### Actual Behaviour

When using Firefox/Windows 10, the override prompt doesn't show up and the app does not override the pre-existing order.

Instead there is a red alert on top of the screen that reads: 1 existing order(s) skipped for Mrs. So and So

(this resembles like the behavior of the app when we try to create an order for someone who already has a one that's been switched to "cancelled" during the CM process.

This causes clients who wants to receive a double order instead of their usual single order to still get only one.

### Steps to reproduce

Use Firefox/Linux
- Create an order of 1 Main/1 dessert for a given client on a given day
- Create an order of 2 Main/2 desserts for the same client on the same day
- When prompted, validate the override of the previous order
- See the successful green alert.
- Delete the order

Then use Firefox/Windows 10
- Create an order of 1 Main/1 dessert for the same client on the same day
- Create an order of 2 Main/2 desserts for the same client on the same day
- Confirm that you are not prompted to override
- Confirm that the previous order was not replaced with the new one

**Comment by guillaumep** [comment]
Pinpointed the issue to this JavaScript code:

https://github.com/santropolroulant/sous-chef/blob/38c0bdbbbec8fb5c6b3c8434add5387f456e6933/souschef/frontend/js/order.js#L8-L19

A modal to warn about overriding the order should show up, but is doesn't.

**Comment by guillaumep** [comment]
The issue seems to be with the usage of the `explicitOriginalTarget` API which only works with Firefox:

https://developer.mozilla.org/en-US/docs/Web/API/Event/explicitOriginalTarget

**Comment by GautamMohanlal** [comment]
Bug is fixed. New Popup is shown when overwriting an order and 'successful order placed' message is sent after updating.
