### ISSUE TITLE
Generate PDF files when downloading them (instead of when viewing the page containing the link)

### ISSUE THREAD

**Issue by guillaumep** [santropolroulant/sous-chef#124]
PDF files (kitchen count, labels, and route sheets) should be generated when the user downloads them, instead of when the user views the page having the download link.

## Rationale

At the moment, PDF files are generated when accessing the Kitchen Count and Routes pages. When the user clicks on the download link, the pre-generated PDF file is downloaded.

This lead to issues in the kitchen count. For example, if the user loads the kitchen count page, then in a separate tab changes orders, come backs to the kitchen count tab and downloads the PDF, the PDF will contain outdated information.

## Other needs

The Roulant staff would also like to be able to access previous versions of generated PDF files, in order to compare the changes between the different versions.

## Acceptance Criterias

- The PDF files are generated at the last moment possible, i.e. when downloading them.
- Each PDF download is archived with the date and time.

**Comment by BeatriceDaudelin** [comment]
Testé en staging 12-03-2024
