### ISSUE TITLE
Can't access kitchen count from staging env. 

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [santropolroulant/sous-chef#24]
### Expected Behaviour

When testing the staging env. we should be able to use all the features available to the prod. version.

### Actual Behaviour
When doing CM on the staging env. we can't see the kitchen count. at step 3 and only get a SERVER 500
![image](https://user-images.githubusercontent.com/21957643/100018940-424e0900-2dab-11eb-885f-c3b0e874a3ac.png)

Fill me in ...

### Steps to reproduce

-generate orders
-enter and confirm ingredients
-click on step 3 for kitchen count

**Comment by guillaumep** [comment]
Will be fixed at the same time as #25.
