### ISSUE TITLE
Can't access Route sheet PDF in staging env.

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [santropolroulant/sous-chef#25]
### Expected Behaviour

When doing step 4 of the kitchen count (Route sheets), you should be able to open the PDF when all routes are confirmed.

### Actual Behaviour

When all routes are confirmed and you click on the Route Sheets pink button, you get a SERVER 500 instead of the pdf loading.

### Steps to reproduce

-Generate orders
-Enter ingredients and confirm
-click on ROUTES (step 4)
-Confirm all routes by opening them and confirming them individually
-Click on the ROUTES pink button to (usually) load the pdf.

**Comment by guillaumep** [comment]
It seems we have a packaging issue, some files are not found. The server gives the following error:

`Cannot open resource "/usr/local/lib/python3.7/dist-packages/souschef/160widthSR-Logo-Screen-PurpleGreen-HI-RGB1.jpg"`

On it.

**Comment by guillaumep** [comment]
Fixed the missing .jpg file, now getting:

`[Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/souschef/kitchen_count.pdf'`

I will need to change the code to write the kitchen count file to a writable directory.

**Comment by guillaumep** [comment]
Fixed.
