### ISSUE TITLE
Allow orders to be cancelled not just deleted

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#70]
As a Sous Chef user, I would like to be able to cancel an order, not just delete an order, when viewing the order detail AND when viewing the list of orders in a client's profile, to ensure that a new order is not generated.

Acceptance criteria:
- When deleting an order that is not yet delivered, the user is informed that this will not prevent a new order from being generated in the Kitchen Count when pressing Generate Orders.
- When canceling an order, the user is informed that the Generate Orders function will not create a new order, and no order will be delivered.

**Comment by guillaumep** [comment]
@brookesantropol I've tried putting a message in the status change dialog when cancelling an order but I could not find a wording that made sense. I think the fact that the canceled order are now displayed in the Kitchen Count makes this message unnecessary.

**Comment by brookesantropol** [comment]
Tested
