### ISSUE TITLE
Display cancelled orders in Kitchen Count

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#72]
As a Sous Chef user, I would like to see a list of cancelled orders for the day when viewing the orders in the Kitchen Count, to allow me to validate that the correct clients will not receive their meal for today.

Acceptance criteria: 
- I should be able to view and edit the orders that have been cancelled.
- The cancelled order list take into account the client name search filter.

**Comment by guillaumep** [comment]
Code completed:
<img width="968" alt="Capture d’écran, le 2021-03-19 à 12 42 48" src="https://user-images.githubusercontent.com/1195230/111814262-a5126580-88b0-11eb-81e7-4218c7031790.png">

**Comment by guillaumep** [comment]
Added acceptance criteria:
- The cancelled order list take into account the client name search filter.

**Comment by guillaumep** [comment]
@brookesantropol Filtering implemented, ready for QA.

**Comment by brookesantropol** [comment]
tested
