### ISSUE TITLE
Indicate when a client is not active on their order in Kitchen Count

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#75]
As a Sous Chef user, I would like to see which orders are for clients that are not active when viewing the list of orders in the Kitchen Count, so that I can easily find them.

Acceptance Criteria:
- The status is added next to the client's name in parenthesis
- A different colour is used to clearly differentiate the order line for such clients

**Comment by guillaumep** [comment]
Code completed:

<img width="955" alt="Capture d’écran, le 2021-03-19 à 11 21 40" src="https://user-images.githubusercontent.com/1195230/111803444-6aef9680-88a5-11eb-9006-1e1beafeff38.png">

**Comment by brookesantropol** [comment]
Put the non-active clients at the top of the list

**Comment by guillaumep** [comment]
@brookesantropol Ready for QA.

**Comment by brookesantropol** [comment]
tested
