### ISSUE TITLE
Cannot cancel an order right after generating the orders

### ISSUE THREAD

**Issue by guillaumep** [santropolroulant/sous-chef#76]
How to reproduce:

1. Open the Kitchen Count.
2. Click on "Generate Orders".
3. Try to cancel an order (by clicking on 🚫 ).

We expect the a dialog to open to confirm the order cancellation, however nothing happens.

Workaround: refresh the page. The 🚫 button will then work.

**Comment by guillaumep** [comment]
Fixed in commit bf80def77bd4105d6ad37959571ada6cd7cda1fc.

**Comment by guillaumep** [comment]
Tested.

**Comment by brookesantropol** [comment]
tested
