### ISSUE TITLE
Highlight inactive clients in the route organization page

### ISSUE THREAD

**Issue by guillaumep** [santropolroulant/sous-chef#77]
As a Sous Chef user, I would like to see clearly which clients are not active when organizing the route, so that I can identify them easily. (I will then be able to either cancel that client's order or change the client status to active.)

Acceptance Criteria:

- A different colour is used to clearly differentiate the line for such clients

**Comment by guillaumep** [comment]
Code completed:

<img width="977" alt="Capture d’écran, le 2021-03-19 à 15 47 06" src="https://user-images.githubusercontent.com/1195230/111834736-65f10e00-88ca-11eb-96c1-cb4a82da57cd.png">

**Comment by brookesantropol** [comment]
tested
