### ISSUE TITLE
Highlight invalid orders in the orders view

### ISSUE THREAD

**Issue by guillaumep** [santropolroulant/sous-chef#78]
As a Sous Chef user I want invalid orders to be highlighted in the order view so that I can act in these orders (cancel them for instance, or change the client's status).

Acceptance criteria

- An invalid order is an ordered order for an inactive order.
- These orders should be highlighted.

**Comment by guillaumep** [comment]
Code completed:

<img width="1040" alt="Capture d’écran, le 2021-03-19 à 16 46 05" src="https://user-images.githubusercontent.com/1195230/111840337-9dfc4f00-88d2-11eb-9ee0-a7ff5a51bf35.png">

**Comment by brookesantropol** [comment]
tested
