### ISSUE TITLE
User can input a quantity of 'None' for an item, and this will crash the billing

### ISSUE THREAD

**Issue by guillaumep** [santropolroulant/sous-chef#79]
To reproduce:

1. Edit an existing order (or create a new one then edit it)
2. Change the quantity of an item: remove the quantity (blank-out the field)
3. Save the changes

As you can see in the order detail, the Total Quantity is set to 'None'. If you create a billing for the period covering the order, the billing crashes (server error).

**Comment by guillaumep** [comment]
Suggested solution: set the Order_item.total_quantity field to not nullable in the database, so Django can properly validate the form.

Default quantity for the field would be 0 for fields already None in the database. This uncovers another bug however: billing items with quantity of 0 or None are still charged.

**Comment by brookesantropol** [comment]
tested
