### ISSUE TITLE
Allow user to delete a Staff Note

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#83]
As a Sous Chef user, I would like to be able to delete unwanted Staff Notes.

Acceptance criteria:
- Staff user is able to delete a note from the Staff Notes
- Super User can go into Admin to undelete the note

**Comment by guillaumep** [comment]
I think I will add a "deleted" flag in the database to implement this, to be on the safe side of things.

**Comment by guillaumep** [comment]
⬆️ Closed as the Roulant deems this no longer necessary for now.
