### ISSUE TITLE
Allow user to indicate if there is an Action item and to update the Action Item status on Staff Notes

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#84]
As a Sous Chef user, I would like to be able to indicate if there is an action item related to a note when creating a note, and be able to mark that action item as completed after the note has been saved.

Acceptance criteria:
- Staff can add an Action Item status ("To do") when creating a note
- Staff can Mark as Complete once note is saved

**Comment by guillaumep** [comment]
This could be for example a check box or a yes/no dropdown.

**Comment by guillaumep** [comment]
⬆️ Closed as the Roulant deems this no longer necessary for now.
