### ISSUE TITLE
Add client delivery status and number of orders to Billing Summary

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#86]
As a Sous Chef user, I would like to be able to see the client's delivery status (Ongoing or Episodic) and the number of Orders placed during the billing period in the Billing summary.

Acceptance criteria
- The heading Delivery Status appears at the top of the Billing Summary table, to the right of Client Name
- The delivery status is listed to the right of each client's name in the Billing Summary
- The heading Orders appears a the top of the Billing Summary table, to the left of Meals
- The number of orders for each client is displayed to the left of the number of meals they have ordered in the Billing Summary

**Comment by lauramarec** [comment]
En utilisation depuis un an
