### ISSUE TITLE
Add All option to Is Read dropdown in Staff Notes

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#87]
As a Sous Chef user, I would like to easily view both Read and Unread notes without having to click the Reset button on the filters.

Acceptance Criteria:
- All is added to the dropdown menu under Is Read

**Comment by guillaumep** [comment]
Not sure I'll be able to do this one, not too sure the lib used allows for that.

**Comment by guillaumep** [comment]
⬆️ Closed as the Roulant deems this no longer necessary for now.
