### ISSUE TITLE
Separate date, author, priority and category fields in display of Staff Notes

### ISSUE THREAD

**Issue by brookesantropol** [santropolroulant/sous-chef#89]
As a Sous Chef user, I would like to see the created date, the user, the category and the priority as separate columns in the list of Staff Notes so that I can easily copy and paste them into a spreadsheet from the list.

Acceptance Criteria
- Date, user, note category and note priority data is displayed in separate columns in list of notes

**Comment by lauramarec** [comment]
En utilisation depuis un an
